version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-docker}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-docker}
      POSTGRES_DB: ${DATABASE_NAME:-user-control}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
