apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/JRC-Capucho/user-control-api.git
    targetRevision: main
    path: .
  destination:
    server: https://Kubernetes.default.svc
    namespace: learnk8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
